/**
 * ExportReport — generates a deception audit report for a conversation.
 *
 * Exports a structured JSON / Markdown report containing:
 *  - Conversation transcript
 *  - Per-message deception scores and types
 *  - Aggregate statistics
 *  - High-risk token highlights
 *  - Steering effectiveness summary
 *
 * In production this would call a backend /api/export endpoint that
 * renders a PDF via WeasyPrint.  For now it generates a downloadable
 * Markdown file client-side.
 */

import React, { useState } from "react";
import { motion } from "framer-motion";
import { ChatMessage, DECEPTION_TYPE_LABELS } from "../types";

interface Props {
  messages: ChatMessage[];
  modelLabel: string;
}

function buildMarkdownReport(messages: ChatMessage[], modelLabel: string): string {
  const now = new Date().toISOString();
  const assistantMsgs = messages.filter((m) => m.role === "assistant" && m.deception);

  const avgScore =
    assistantMsgs.length > 0
      ? assistantMsgs.reduce((s, m) => s + (m.deception?.score ?? 0), 0) /
        assistantMsgs.length
      : 0;

  const typeCounts: Record<string, number> = {};
  assistantMsgs.forEach((m) => {
    const t = m.deception?.deception_type ?? "none";
    typeCounts[t] = (typeCounts[t] ?? 0) + 1;
  });

  const lines: string[] = [
    "# DeceptiScope v2 — Deception Audit Report",
    "",
    `**Generated:** ${now}`,
    `**Model:** ${modelLabel}`,
    `**Total turns:** ${assistantMsgs.length}`,
    `**Average deception score:** ${(avgScore * 100).toFixed(1)}%`,
    "",
    "## Deception Type Distribution",
    "",
    ...Object.entries(typeCounts).map(
      ([t, n]) =>
        `- **${DECEPTION_TYPE_LABELS[t as keyof typeof DECEPTION_TYPE_LABELS] ?? t}**: ${n} occurrence(s)`
    ),
    "",
    "## Conversation Transcript",
    "",
  ];

  messages.forEach((msg, i) => {
    lines.push(`### Turn ${Math.floor(i / 2) + 1} — ${msg.role === "user" ? "User" : "Assistant"}`);
    lines.push("");
    lines.push(msg.content);
    lines.push("");

    if (msg.deception) {
      const d = msg.deception;
      lines.push(
        `> **Deception score:** ${(d.score * 100).toFixed(1)}% | ` +
          `**Type:** ${DECEPTION_TYPE_LABELS[d.deception_type] ?? d.deception_type} | ` +
          `**Confidence:** ${(d.confidence * 100).toFixed(0)}%`
      );
      if (d.explanation) lines.push(`> ${d.explanation}`);
      if (d.high_risk_tokens.length > 0) {
        lines.push(
          `> **High-risk tokens:** ${d.high_risk_tokens
            .slice(0, 5)
            .map((t) => `\`${t.token}\` (${(t.risk_score * 100).toFixed(0)}%)`)
            .join(", ")}`
        );
      }
      lines.push("");
    }
  });

  lines.push("---");
  lines.push("*Report generated by DeceptiScope v2 — Schmidt Sciences 2026 Interpretability RFP*");

  return lines.join("\n");
}

export const ExportReport: React.FC<Props> = ({ messages, modelLabel }) => {
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    setExporting(true);
    await new Promise((r) => setTimeout(r, 400)); // brief animation

    const md = buildMarkdownReport(messages, modelLabel);
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `deceptiscope-audit-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);

    setExporting(false);
  };

  const handleExportJSON = () => {
    const data = {
      generated: new Date().toISOString(),
      model: modelLabel,
      messages: messages.map((m) => ({
        role:      m.role,
        content:   m.content,
        timestamp: m.timestamp,
        deception: m.deception ?? null,
      })),
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `deceptiscope-audit-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const hasMessages = messages.some((m) => m.role === "assistant");

  return (
    <div className="bg-ds-surface border border-ds-border rounded-xl p-4 space-y-3">
      <h2 className="text-sm font-semibold text-ds-text uppercase tracking-wider">
        Export Report
      </h2>

      <p className="text-xs text-ds-muted leading-relaxed">
        Generate a deception audit report for this conversation. Includes
        per-message scores, type breakdown, and high-risk token highlights.
      </p>

      <div className="flex gap-2">
        <motion.button
          whileTap={{ scale: 0.97 }}
          onClick={handleExport}
          disabled={!hasMessages || exporting}
          className="flex-1 py-2 rounded-lg bg-ds-accent text-ds-bg font-semibold text-sm
                     disabled:opacity-40 disabled:cursor-not-allowed hover:bg-blue-400
                     transition-colors"
        >
          {exporting ? "Generating…" : "Export Markdown"}
        </motion.button>

        <motion.button
          whileTap={{ scale: 0.97 }}
          onClick={handleExportJSON}
          disabled={!hasMessages}
          className="flex-1 py-2 rounded-lg border border-ds-border text-ds-text text-sm
                     disabled:opacity-40 disabled:cursor-not-allowed hover:border-ds-accent
                     transition-colors"
        >
          Export JSON
        </motion.button>
      </div>

      {!hasMessages && (
        <p className="text-xs text-ds-muted/60 text-center">
          No messages to export yet.
        </p>
      )}
    </div>
  );
};
